### ISSUE TITLE
Can I add a react-native button component to the Scanner ?

### ISSUE THREAD

**Issue by thidasapankaja** [blinkcard/blinkcard-react-native#10]
I'm doing a POC with a trial version and it works great. However, I tried to find a documentation to follow to implement this. But couldn't find one (with the methods and stuff). Had to look at example app and try to understand.

Is there any documentation with exposed methods rather than in the example app ?

And the other thing is, I have a requirement to add a button to the scanner screen, where user can click on that and navigate to a specific screen (stopping the scan midway). Is this possible ? Can I add a custom react-native button ?

TIA

**Comment by mparadina** [comment]
Hi @thidasapankaja 

Unfortunately, adding custom UI elements to BlinkCard overlays is not possible directly.
The features you can modify on the overlay can be found [here](https://github.com/blinkcard/blinkcard-react-native/blob/main/BlinkCard/overlays/blinkCardOverlays.js#L10-L75).

In order to create your own custom overlay, you would need to do it via native code (instructions for [Android](https://github.com/blinkcard/blinkcard-android?tab=readme-ov-file#recognizer-runner-view) & [iOS](https://github.com/blinkcard/blinkcard-ios?tab=readme-ov-file#using-custom-overlay-viewcontroller)), and then wrap it to so that it can be used via the React-Native platform.

**Comment by thidasapankaja** [comment]
Thanks for the quick response @mparadina 

Understood. Need to get clarified another thing. As the trial version MicroBlink branding are displayed in the overlay. Does it being removed if we go to a paid version ?
And is there a way to disable scanning the Back side of the card  and only the rest of the details (from the Front side) can be captured and close ?

**Comment by mparadina** [comment]
@thidasapankaja for the first question, yes, the Microblink watermarks displayed on the scanning screen are removed once you purchase and implement a production license key in the SDK configuration.

For the second question, yes, that is also possible. You just need to limit the BlinkCard recognizer to extract the information that is located on the front side of the card. The only mandatory field for the extraction process is the card number. For example, in the [DirectAPI single-side example](https://github.com/blinkcard/blinkcard-react-native/blob/main/sample_files/index.js#L185-L189), you can see that the recognizer is only limited to extracting the card number and the card owner's name.
